name:  CI
env:
  # Common versions
  GO_VERSION: "1.16"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.1
      with:
       go-version: ${{ env.GO_VERSION }}
    - name: Build Binaries
      run: |
          make build ARCH=amd64 
